Null coalesce to selected to allow underlying command handle missing tag
This gives:
      INFO  No publishable resources for tag [test].
Instead of:
    ErrorException: Undefined array key "test"