Update deployment workflow to pull changes before commit
Should fix the following:

error: failed to push some refs to 'https://github.com/hydephp/develop'
hint: Updates were rejected because the tip of your current branch is behind

See https://github.com/EndBug/add-and-commit